<a href="https://colab.research.google.com/github/Mnikito/4016/blob/main/HW1/HW1_Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# Homework 1    Problem 1

import torch

In [3]:
import imageio
from PIL import Image
import torchvision.transforms as transforms

# 1b Load Images and Convert to Tensor
#Red Images
img_arr  = imageio.imread("/content/drive/MyDrive/4106/HW1/red1.jpg")
img_arr2 = imageio.imread("/content/drive/MyDrive/4106/HW1/red2.jpg")
img_arr3 = imageio.imread("/content/drive/MyDrive/4106/HW1/red3.jpg")

#Green Images
img_arr4 = imageio.imread("/content/drive/MyDrive/4106/HW1/green1.jpg")
img_arr5 = imageio.imread("/content/drive/MyDrive/4106/HW1/green2.jpg")
img_arr6 = imageio.imread("/content/drive/MyDrive/4106/HW1/green3.jpg")

#Blue Images
img_arr7  = imageio.imread("/content/drive/MyDrive/4106/HW1/blue1.jpg")
img_arr8 = imageio.imread("/content/drive/MyDrive/4106/HW1/blue2.jpg")
img_arr9 = imageio.imread("/content/drive/MyDrive/4106/HW1/blue3.jpg")

# Define transform to convert the image to PyTorch Tensor
transform = transforms.ToTensor()

# Convert image to PyTorch Tensor (Image Tensor)
#Red
img_t = transform(img_arr)
img_t2 = transform(img_arr2)
img_t3 = transform(img_arr3) 

#Green
img_t4 = transform(img_arr4)
img_t5 = transform(img_arr5)
img_t6 = transform(img_arr6)

#Blue 
img_t7 = transform(img_arr7)
img_t8 = transform(img_arr8)
img_t9 = transform(img_arr9)

In [4]:
# Finding average of each color
#Red
r1_brightness = torch.mean(img_t)
r2_brightness = torch.mean(img_t2)
r3_brightness = torch.mean(img_t3)
r1_data = torch.mean(img_t, dim =[1,2])
r2_data = torch.mean(img_t2,dim =[1,2])
r3_data = torch.mean(img_t3,dim =[1,2])

#Green
g1_brightness = torch.mean(img_t4)
g2_brightness = torch.mean(img_t5)
g3_brightness = torch.mean(img_t6)
g1_data = torch.mean(img_t4,dim =[1,2])
g2_data = torch.mean(img_t5,dim =[1,2])
g3_data = torch.mean(img_t6,dim =[1,2])

#Blue
b1_brightness = torch.mean(img_t7)
b2_brightness = torch.mean(img_t8)
b3_brightness = torch.mean(img_t9)
b1_data = torch.mean(img_t7, dim =[1,2])
b2_data = torch.mean(img_t8, dim =[1,2])
b3_data = torch.mean(img_t9, dim =[1,2])

In [5]:
# Printing Each One
#Red Brightness
print("\nRed Photo Brightnesses")
print(r1_brightness)
print(r2_brightness)
print(r3_brightness)
#Red Colors
print("\nRed Photo Mean Values")
print(r1_data)
print(r2_data)
print(r3_data)

#Green Brightness
print("\nGreen Photo Brightnesses")
print(g1_brightness)
print(g2_brightness)
print(g3_brightness)

#Green Colors
print("\nGreen Photo Mean Values")
print(g1_data)
print(g2_data)
print(g3_data)

#Blue Brightness
print("\nBlue Photo Brightnesses")
print(b1_brightness)
print(b2_brightness)
print(b3_brightness)

#Blue
print("\nBlue Photo Mean Values")
print(b1_data)
print(b2_data)
print(b3_data)


Red Photo Brightnesses
tensor(0.4349)
tensor(0.3794)
tensor(0.3779)

Red Photo Mean Values
tensor([0.6617, 0.3274, 0.3156])
tensor([0.7598, 0.1817, 0.1968])
tensor([0.7432, 0.1882, 0.2023])

Green Photo Brightnesses
tensor(0.5279)
tensor(0.5480)
tensor(0.6202)

Green Photo Mean Values
tensor([0.6329, 0.6296, 0.3213])
tensor([0.6340, 0.6382, 0.3720])
tensor([0.4649, 0.7379, 0.6576])

Blue Photo Brightnesses
tensor(0.6384)
tensor(0.4861)
tensor(0.5912)

Blue Photo Mean Values
tensor([0.6715, 0.6361, 0.6075])
tensor([0.4523, 0.5210, 0.4848])
tensor([0.5956, 0.5990, 0.5789])
